uploads = []

[[generated]]
id = "zy2NzfY_NKN2oUC-XJeql"
uri = "file://artifacts/epic-poetry-mobile/assets/images/icon.png"
type = "image"
title = "epic poetry app icon"

[[outputs]]
id = "nro3DNhDE5e1Y8uvLVYuH"
uri = "file://docs/SRS.md"
type = "text"
title = "Software Requirements Specification (SRS)"

[[outputs]]
id = "5ZJCHtYbDNZ5anhUKbKad"
uri = "file://docs/DEVELOPER_GUIDE.md"
type = "text"
title = "Developer Guide"

[[outputs]]
id = "IU7wf7LEjrg5bq3thWpR_"
uri = "file://docs/SRS.docx"
type = "word_document"
title = "SRS - Epic Poetry Cafe (Word)"

[[outputs]]
id = "FPMma-y7M-Ak0YLcOC27h"
uri = "file://docs/DEVELOPER_GUIDE.docx"
type = "word_document"
title = "Developer Guide - Epic Poetry Cafe (Word)"

[[outputs]]
id = "uILC1LAwrCvMMCm8YfnPO"
uri = "file://exports/Epic-Poetry-Cafe-User-Guide.docx"
type = "word_document"
title = "Epic Poetry Cafe — User Guide & Feature Reference"
